package test.entities;
// Generated 24.6.2015 13:49:31 by Hibernate Tools 4.3.1



/**
 * Branch generated by hbm2java
 */
public class Branch  implements java.io.Serializable {


     private Integer id;
     private User user;
     private String name;

    public Branch() {
    }

	
    public Branch(User user) {
        this.user = user;
    }
    public Branch(User user, String name) {
       this.user = user;
       this.name = name;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public User getUser() {
        return this.user;
    }
    
    public void setUser(User user) {
        this.user = user;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }




}


