package test.entities;
// Generated 24.6.2015 13:49:31 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * NoteId generated by hbm2java
 */
public class NoteId  implements java.io.Serializable {


     private int id;
     private String registrationIco;
     private Date registrationRegDate;

    public NoteId() {
    }

    public NoteId(int id, String registrationIco, Date registrationRegDate) {
       this.id = id;
       this.registrationIco = registrationIco;
       this.registrationRegDate = registrationRegDate;
    }
   
    public int getId() {
        return this.id;
    }
    
    public void setId(int id) {
        this.id = id;
    }
    public String getRegistrationIco() {
        return this.registrationIco;
    }
    
    public void setRegistrationIco(String registrationIco) {
        this.registrationIco = registrationIco;
    }
    public Date getRegistrationRegDate() {
        return this.registrationRegDate;
    }
    
    public void setRegistrationRegDate(Date registrationRegDate) {
        this.registrationRegDate = registrationRegDate;
    }




}


