package test.entities;
// Generated 24.6.2015 13:49:31 by Hibernate Tools 4.3.1



/**
 * Note generated by hbm2java
 */
public class Note  implements java.io.Serializable {


     private NoteId id;
     private Registration registration;
     private String createdDate;
     private String text;

    public Note() {
    }

	
    public Note(NoteId id, Registration registration) {
        this.id = id;
        this.registration = registration;
    }
    public Note(NoteId id, Registration registration, String createdDate, String text) {
       this.id = id;
       this.registration = registration;
       this.createdDate = createdDate;
       this.text = text;
    }
   
    public NoteId getId() {
        return this.id;
    }
    
    public void setId(NoteId id) {
        this.id = id;
    }
    public Registration getRegistration() {
        return this.registration;
    }
    
    public void setRegistration(Registration registration) {
        this.registration = registration;
    }
    public String getCreatedDate() {
        return this.createdDate;
    }
    
    public void setCreatedDate(String createdDate) {
        this.createdDate = createdDate;
    }
    public String getText() {
        return this.text;
    }
    
    public void setText(String text) {
        this.text = text;
    }




}


