package test.entities;
// Generated 24.6.2015 13:49:31 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * RegistrationId generated by hbm2java
 */
public class RegistrationId  implements java.io.Serializable {


     private String ico;
     private Date regDate;

    public RegistrationId() {
    }

    public RegistrationId(String ico, Date regDate) {
       this.ico = ico;
       this.regDate = regDate;
    }
   
    public String getIco() {
        return this.ico;
    }
    
    public void setIco(String ico) {
        this.ico = ico;
    }
    public Date getRegDate() {
        return this.regDate;
    }
    
    public void setRegDate(Date regDate) {
        this.regDate = regDate;
    }




}


