package test.entities;
// Generated 24.6.2015 13:49:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Registration generated by hbm2java
 */
public class Registration  implements java.io.Serializable {


     private RegistrationId id;
     private RegState regState;
     private String companyName;
     private Unit unit;
     private Set notes = new HashSet(0);

    public Registration() {
    }

	
    public Registration(RegistrationId id, RegState regState, Unit unit) {
        this.id = id;
        this.regState = regState;
        this.unit = unit;
    }
    public Registration(RegistrationId id, RegState regState, String companyName, Unit unit, Set notes) {
       this.id = id;
       this.regState = regState;
       this.companyName = companyName;
       this.unit = unit;
       this.notes = notes;
    }
   
    public RegistrationId getId() {
        return this.id;
    }
    
    public void setId(RegistrationId id) {
        this.id = id;
    }
    public RegState getRegState() {
        return this.regState;
    }
    
    public void setRegState(RegState regState) {
        this.regState = regState;
    }
    public String getCompanyName() {
        return this.companyName;
    }
    
    public void setCompanyName(String companyName) {
        this.companyName = companyName;
    }
    
    public Unit getUnit() {
        return this.unit;
    }
    
    public void setUnit(Unit unit) {
        this.unit = unit;
    }
    public Set getNotes() {
        return this.notes;
    }
    
    public void setNotes(Set notes) {
        this.notes = notes;
    }




}


