package test.entities;
// Generated 24.6.2015 13:49:31 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * RegState generated by hbm2java
 */
public class RegState  implements java.io.Serializable {


     private Integer id;
     private String name;
     private Set registrations = new HashSet(0);

    public RegState() {
    }

    public RegState(String name, Set registrations) {
       this.name = name;
       this.registrations = registrations;
    }
   
    public Integer getId() {
        return this.id;
    }
    
    public void setId(Integer id) {
        this.id = id;
    }
    public String getName() {
        return this.name;
    }
    
    public void setName(String name) {
        this.name = name;
    }
    public Set getRegistrations() {
        return this.registrations;
    }
    
    public void setRegistrations(Set registrations) {
        this.registrations = registrations;
    }




}


