package test.entities;
// Generated 24.6.2015 13:49:31 by Hibernate Tools 4.3.1



/**
 * Unit generated by hbm2java
 */
public class Unit  implements java.io.Serializable {


     private UnitId id;

    public Unit() {
    }

    public Unit(UnitId id) {
       this.id = id;
    }
   
    public UnitId getId() {
        return this.id;
    }
    
    public void setId(UnitId id) {
        this.id = id;
    }




}


