package test.entities;
// Generated 24.6.2015 13:49:31 by Hibernate Tools 4.3.1



/**
 * UnitId generated by hbm2java
 */
public class UnitId  implements java.io.Serializable {


     private int branchId;
     private int userId;

    public UnitId() {
    }

    public UnitId(int branchId, int userId) {
       this.branchId = branchId;
       this.userId = userId;
    }
   
    public int getBranchId() {
        return this.branchId;
    }
    
    public void setBranchId(int branchId) {
        this.branchId = branchId;
    }
    public int getUserId() {
        return this.userId;
    }
    
    public void setUserId(int userId) {
        this.userId = userId;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof UnitId) ) return false;
		 UnitId castOther = ( UnitId ) other; 
         
		 return (this.getBranchId()==castOther.getBranchId())
 && (this.getUserId()==castOther.getUserId());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getBranchId();
         result = 37 * result + this.getUserId();
         return result;
   }   


}


